name: Deploy cloudresume
on:
  push:
    branches:
      - main

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
jobs:
  deploy_infra:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::494409419459:role/gh-actions-role
          aws-region: ap-southeast-1

      - name: Install dependencies
        run: npm install -g aws-cdk
      - name: Install required packages
        run: pip install -r requirements.txt
      - name: Synth stack
        run: cdk synth
      - name: Deploy stack
        run: cdk deploy --all --require-approval never
