name: Deploy cloudresume
on:
  push:
    branches:
      - main

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
jobs:
  deploy_infra:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::494409419459:role/gh-actions-role
          aws-region: ap-southeast-1

      - name: Install dependencies
        run: npm install -g aws-cdk
      - name: Install required packages
        run: pip install -r requirements.txt
      - name: Synth stack
        run: cdk synth
      - name: Deploy stack
        run: cdk deploy --all --require-approval never

  build_and_deploy_site:
    needs: [deploy_infra]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::494409419459:role/gh-actions-role
          aws-region: ap-southeast-1

      - name: Get bucket name, distribution id and api url
        run: |
          S3_BUCKET=$(aws cloudformation describe-stacks --stack-name cloudresume-frontend --query "Stacks[0].Outputs[?OutputKey=='CloudresumeBucketName'].OutputValue" --output text)
          DISTRIBUTION_ID=$(aws cloudformation describe-stacks --stack-name cloudresume-frontend --query "Stacks[0].Outputs[?OutputKey=='CloudresumeCloudfrontDistributionId'].OutputValue" --output text)
          API_URL=$(aws cloudformation describe-stacks --stack-name cloudresume-backend --query "Stacks[0].Outputs[?OutputKey=='VisitorCounterAPIURL'].OutputValue" --output text)

          echo "DISTRIBUTION_ID=$DISTRIBUTION_ID" >> $GITHUB_ENV
          echo "S3_BUCKET=$S3_BUCKET" >> $GITHUB_ENV
          echo "API_URL=$API_URL" >> $GITHUB_ENV

      - name: Build the app
        run: |
          npm install
          VITE_API_URL=$API_URL npm run build

      - name: Deploy to S3_BUCKET
        run: aws s3 sync ./dist/ s3://$S3_BUCKET --delete

      - name: Invalidate Cloudfront
        run: aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"

  run_tests:
    needs: [deploy_infra, build_and_deploy_site]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tests
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v5
